### PR TITLE
add how to implement sliding session refreshes with apollo and react blog post

### PR DESCRIPTION
**Pull request by B-Evans99**
I wasn't sure about whether to import the `MailingListForm` or to add it to the local `./components`. I've gone with the latter @okanji but if you could provide some advice that would be much appreciated.. :-)

We're hoping to have this up by EOD October 13th.

https://www.notion.so/twostoryrobot/How-to-implement-sliding-session-refreshes-with-Apollo-and-React-c256e5c3fa7d4c089dea46962a325094

### CODE REVIEW

**Comment by okanji** [comment]
Hey @B-Evans99, thats the old subscription component, should have removed it. I will make the necessary changes

**Comment by okanji** [comment]
@B-Evans99 I have removed the old component. The one that should be used is `NewsLetter.js`. 

Do you want the subscribe component to be at the bottom of every blog post or just this one? If you want it in every component it should be put in `src/components/blog/BlogLayout.js`.

**Comment by B-Evans99** [comment]
@okanji Ooh, I was just adding it to this post but I would totally support having it on every one. Let me go do that.

**Comment by okanji** [comment]
@B-Evans99 I mean it's just something I though about I'm not sure if its something that the rest of the team wants?? Feel free to add it to your post but maybe we run this by the rest if want to add it as a general feature

**Comment by okanji** [comment]
@B-Evans99 good stuff having the background colour match the blog

**Comment by B-Evans99** [comment]
@okanji I don't have access to Vercel so I'm not sure why it's hanging, but in my local environment all looks well. I'm going to merge this at 5 unless I hear from you that I shouldn't ':-)

**Pull request merged**
